language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t adityeah8969/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true USERNAME/react-test npm test

after_success:
  - docker build -t adityeah8969/multi-client ./client
  - docker build -t adityeah8969/multi-nginx ./nginx
  - docker build -t adityeah8969/multi-server ./server
  - docker build -t adityeah8969/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push adityeah8969/multi-client
  - docker push adityeah8969/multi-nginx
  - docker push adityeah8969/multi-server
  - docker push adityeah8969/multi-worker
